# Generated by Django 2.1.2 on 2020-03-26 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category Name Ar')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category Name En')),
                ('show', models.NullBooleanField(verbose_name='show')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country Ar')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country En')),
                ('display', models.BooleanField(default=True, verbose_name='Display')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title Ar')),
                ('title_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title En')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='Slug')),
                ('body_ar', models.TextField(blank=True, null=True, verbose_name='Body Ar')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Body En')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Price')),
                ('allow_offer', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Offer')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('rejected_reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('view', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Viewed')),
                ('ip_address', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, verbose_name='ip address')),
                ('added_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By')),
                ('added_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Added Date')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Updated By')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Country')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Name')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('gender', models.CharField(blank=True, choices=[('', '---'), ('M', 'Male'), ('F', 'Female')], default='', max_length=10, null=True, verbose_name='Gender')),
                ('mobile', models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobile')),
                ('banck_account', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bank Account')),
                ('website', models.URLField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkedin')),
                ('youtube', models.CharField(blank=True, max_length=100, null=True, verbose_name='Youtube')),
                ('google_plus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Plus')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
