# Generated by Django 2.1.2 on 2020-03-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='slug_ar',
            field=models.SlugField(blank=True, max_length=250, null=True, verbose_name='Slug Ar'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=250, null=True, verbose_name='Slug En'),
        ),
    ]
