# Generated by Django 2.1.2 on 2020-03-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200326_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, verbose_name='Slug Ar'),
        ),
    ]
