# Generated by Django 2.1.2 on 2020-03-26 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200326_0551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug_en',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_ar',
        ),
    ]
