# Generated by Django 2.1.2 on 2020-03-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200326_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='slug_en',
        ),
    ]
