# Generated by Django 2.1.2 on 2020-03-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200326_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Image'),
        ),
    ]
