# Generated by Django 2.1.2 on 2020-03-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20200327_0214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductIamge',
            new_name='ProductImage',
        ),
    ]
