# Generated by Django 2.1.2 on 2020-03-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_updated_by',
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
    ]
