# Generated by Django 2.1.2 on 2020-03-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_product_slug_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Viewed'),
        ),
    ]
