# Generated by Django 2.1.2 on 2020-03-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20200331_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Viewed'),
        ),
    ]
